### PR TITLE
feat: Ask for write only permissions when saving photos in Ios

### LINKED ISSUE #265: Why is NSPhotoLibraryUsageDescription required for save()?
On iOS 14 my users need to save to the camera roll. `CameraRoll.save()` is prompting for full library access (`NSPhotoLibraryUsageDescription`) access, but should instead be prompted for the more restrictive write-only access (`NSPhotoLibraryAddUsageDescription`) since they are only saving.

It's confusing users because they are just saving a picture, not uploading anything. They get the prompt to "Select Photos..." or "Allow Access to All Photos". which makes no sense when all they want to do is save. I know this package can't control those messages, but is it possible to use the more appropriate and restrictive write-only permission instead?

### LINKED ISSUE #279: on IOS 14+, the `getPhotos()` cannot exclude the restricted photos on limited access permission
iOS 14 introduced the `selected photos` permission on photo library, which restricted the photos to be access from the app.

### PR DESCRIPTION
**Pull request by Masadow**
# Summary

Fixes #265

Could be enhanced to fix #279 as well. It's pretty well explained [here](https://developer.apple.com/documentation/photokit/delivering_a_great_privacy_experience_in_your_photos_app?language=objc).

Also from the same link, album management seems to be a nightmare and still require read/write permissions although you just like to save. I could not find any workaround :(

### What's required for testing (prerequisites)?

Nothing particular

### What are the steps to reproduce (after prerequisites)?

Everything resides in `CameraRoll.save`. If you specified an album, behaviour will remain unchanged.
Otherwise, you'll see the following write only permission modal.

IMG_20210215_125519

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Review by MarcoScabbiolo — APPROVED** [review]
Changes look ok, haven't tested it.

**Comment by ineguttormsen** [comment]
Looking forward to this fix 🎉  Can we expect a merge/release anytime soon?

**Comment by Fan** [comment]
Just tested it and everything seems to be working fine! Any updates to this being merged in?

**Comment by schlafnie** [comment]
any plans to merge and release this?

**Comment by dasaco** [comment]
Will this be merged?

**Comment by Dovydastc** [comment]
Sounds great!

**Comment by MarcoScabbiolo** [comment]
@bartolkaruza can u release this? Not sure if just merging is enough

**Comment by dexterowy** [comment]
I'm waiting with release of my app because of that permissions issue 😃 ! Please merge it

**Comment by dklymenk** [comment]
It would be nice to get this PR updated. The patch no longer applies to the most recent version.

Thank you.

**Comment by AndreiDanilkovich** [comment]
any updates on this?

**Comment by idrissakhi** [comment]
@Masadow would you resolve the conflicts so we can merge this PR please 🙂😉

**Comment by idrissakhi** [comment]
This is a duplicate and main PR is merged already.

**Pull request closed without merging**
