### PR TITLE
Include assets originating from an iCloud Shared Album. iOS only.

### PR DESCRIPTION
**Pull request by zatteo**
# Summary

Add a `includeSharedAlbums` boolean parameter in `getPhotos` to allow to get images and videos in iCloud Shared Albums on iOS.

## Test Plan

- Receive an album sharing
- Without PR : you do not get them with `getPhotos`
- With PR : you get them with `getPhotos` 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌  (not relevant)   |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Review by Arjan-Zuidema — CHANGES_REQUESTED** [review]
Can you add the include option to the example? The FabricExample is currently the only one that is working. I am (slowly) working on making everything working again

Installation and starting steps:
```
cd FabricExample
cd ios
pod install
cd. ..
yarn start
yarn ios
```

**Comment by zatteo** [comment]
Sure I will try to add this the next days.

**Comment by zatteo** [comment]
@Arjan-Zuidema Hi, what do you think about my last commit?

**Review by Arjan-Zuidema — APPROVED** [review]

**Comment by Arjan-Zuidema** [comment]
LGTM!

**Pull request merged**
