### PR TITLE
feat: Properly copy over EXIF and GPS metadata tags when saving

### LINKED ISSUE #598: `CameraRoll.save(...)` strips EXIF Metadata
Hey all, I've been using react-native-cameraroll to test VisionCamera's Example app.

I noticed that some EXIF tags (such as GPS tags) are stripped out of the image when saving it to the Gallery.
Is that intentional?

The image's original EXIF tags:

```
ExifTool Version Number         : 12.76
File Name                       : D7760E44-17A6-4B97-B7DE-C8C1623A971B.jpeg
Directory                       : .
File Size                       : 1250 kB
File Modification Date/Time     : 2024:03:20 11:53:11+01:00
File Access Date/Time           : 2024:03:20 11:53:23+01:00
File Inode Change Date/Time     : 2024:03:20 11:53:22+01:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Big-endian (Motorola, MM)
Make                            : Apple
Camera Model Name               : iPhone 8
Orientation                     : Rotate 90 CW
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : 15.4.1
Modify Date                     : 2024:03:20 11:53:11
Host Computer                   : iPhone 8
Y Cb Cr Positioning             : Centered
Exposure Time                   : 1/60
F Number                        : 1.8
Exposure Program                : Program AE
ISO                             : 200
Exif Version                    : 0232
Date/Time Original              : 2024:03:20 11:53:11
Create Date                     : 2024:03:20 11:53:11
Offset Time                     : +01:00
Offset Time Original            : +01:00
Offset Time Digitized           : +01:00
Components Configuration        : Y, Cb, Cr, -
Shutter Speed Value             : 1/60
Aperture Value                  : 1.8
Brightness Value                : 2.194675122
Exposure Compensation           : 0
Metering Mode                   : Multi-segment
Flash                           : Off, Did not fire
Focal Length                    : 4.0 mm
Subject Area                    : 1920 1079 2112 950
Maker Note Version              : 14
Run Time Flags                  : Valid
Run Time Value                  : 78736085096416
Run Time Epoch                  : 0
Run Time Scale                  : 1000000000
AE Stable                       : Yes
AE Target                       : 177
AE Average                      : 184
AF Stable                       : Yes
Acceleration Vector             : 0.006664792069 -0.8730471732 -0.4841696918
Focus Distance Range            : 0.26 - 0.61 m
OIS Mode                        : 3
Image Capture Type              : ProRAW
Live Photo Video Index          : 0
Signal To Noise Ratio           : 0
Photo Identifier                : 45A1C60C-5C47-4E96-A4D8-A84267898557
Focus Position                  : 82
Semantic Style Rendering Ver    : True
Sub Sec Time Original           : 053
Sub Sec Time Digitized          : 053
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 3840
Exif Image Height               : 2160
Sensing Method                  : One-chip color area
Scene Type                      : Directly photographed
Exposure Mode                   : Auto
White Balance                   : Auto
Focal Length In 35mm Format     : 32 mm
Scene Capture Type              : Standard
Lens Info                       : 3.99000001mm f/1.8
Lens Make                       : Apple
Lens Model                      : iPhone 8 back camera 3.99mm f/1.8
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Altitude Ref                : Above Sea Level
GPS Dilution Of Precision       : 35
GPS Img Direction Ref           : True North
GPS Img Direction               : ******
GPS Date Stamp                  : ********
Image Width                     : 3840
Image Height                    : 2160
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Run Time Since Power Up         : 21:52:16
Aperture                        : 1.8
Image Size                      : 3840x2160
Megapixels                      : 8.3
Scale Factor To 35 mm Equivalent: 8.0
Shutter Speed                   : 1/60
Create Date                     : 2024:03:20 11:53:11.053+01:00
Date/Time Original              : 2024:03:20 11:53:11.053+01:00
Modify Date                     : 2024:03:20 11:53:11+01:00
GPS Altitude                    : 170.3 m Above Sea Level
GPS Latitude                    : ********" N
GPS Longitude                   : ********" E
Circle Of Confusion             : 0.004 mm
Field Of View                   : 58.7 deg
Focal Length                    : 4.0 mm (35 mm equivalent: 32.0 mm)
GPS Position                    : 48 deg 11' 38.95" N, 16 deg 24' 8.38" E
Hyperfocal Distance             : 2.36 m
Light Value                     : 6.6
Lens ID                         : iPhone 8 back camera 3.99mm f/1.8
```

And when saved to the Gallery, it only has the following EXIF tags remaining:

```
ExifTool Version Number         : 12.76
File Name                       : IMG_8247.JPG
Directory                       : .
File Size                       : 1229 kB
File Modification Date/Time     : 2024:03:20 11:51:06+01:00
File Access Date/Time           : 2024:03:20 11:51:13+01:00
File Inode Change Date/Time     : 2024:03:20 11:51:11+01:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Exif Byte Order                 : Big-endian (Motorola, MM)
Orientation                     : Rotate 90 CW
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Modify Date                     : 2024:03:20 11:50:57
Exif Version                    : 0221
Date/Time Original              : 2024:03:20 11:50:57
Create Date                     : 2024:03:20 11:50:57
Offset Time                     : +01:00
Offset Time Original            : +01:00
Offset Time Digitized           : +01:00
Components Configuration        : Y, Cb, Cr, -
Sub Sec Time                    : 047
Sub Sec Time Original           : 047
Sub Sec Time Digitized          : 047
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 3840
Exif Image Height               : 2160
Scene Capture Type              : Standard
Current IPTC Digest             : 00c86e4256eb6ab8997080b536a4cc6c
Coded Character Set             : UTF8
Application Record Version      : 2
Digital Creation Time           : 11:50:57
Digital Creation Date           : 2024:03:20
Date Created                    : 2024:03:20
Time Created                    : 11:50:57
IPTC Digest                     : 00c86e4256eb6ab8997080b536a4cc6c
Image Width                     : 3840
Image Height                    : 2160
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 3840x2160
Megapixels                      : 8.3
Create Date                     : 2024:03:20 11:50:57.047+01:00
Date/Time Original              : 2024:03:20 11:50:57.047+01:00
Modify Date                     : 2024:03:20 11:50:57.047+01:00
Date/Time Created               : 2024:03:20 11:50:57
Digital Creation Date/Time      : 2024:03:20 11:50:57
```

Does CameraRoll provide a way to preserve such EXIF tags?

### PR DESCRIPTION
**Pull request by mrousavy**
# Summary

Fixes #598 by properly copying over EXIF and GPS metadata tags when saving images. 

Instead of loading the file as NSData and converting it to a UIImage, we directly pass the image path to the `PHAssetChangeRequest`, which also takes EXIF and GPS tags into account.

## Test Plan

Just call save with EXIF tags. It works now.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by mrousavy** [comment]
Hey @bartolkaruza - can you let me know if this makes sense? It works for me :)

**Comment by Arjan-Zuidema** [comment]
Hi @mrousavy thanks for this pull request! Looks like you have not checked any of the boxes on the checklist. I assume you have tested this?
Will give it a test at the end of the week

**Comment by mrousavy** [comment]
Yes - I did test it for ShadowLens, works like a charm for jpg.

I did not test webP images though

**Pull request merged**
