### PR TITLE
Added UTs for CameraRollIOSPermission file

### PR DESCRIPTION
**Pull request by SparshaSaha**
# Summary

Added some Unit Test cases for one of the files

## Test Plan

We should be able to test the test cases in CircleCI

### What's required for testing (prerequisites)?
NA

### What are the steps to reproduce (after prerequisites)?
NA

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by SparshaSaha** [comment]
@bartolkaruza can you help with some reviews here?

**Comment by bartolkaruza** [comment]
@idrissakhi @Arjan-Zuidema @santhoshvai

**Review by santhoshvai — APPROVED** [review]

**Comment by santhoshvai** [comment]
@bartolkaruza I am unable to merge it myself.. but this LGTM 👍 thanks @SparshaSaha

**Comment by bartolkaruza** [comment]
@santhoshvai I've added you now, thanks for looking into this!

**Pull request merged**
