### PR TITLE
Added basic SmartAlbum support for iOS (conflicts resolved)

### PR DESCRIPTION
**Pull request by jp-23**
# Summary

This PR resolves the conflicts from [324](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/324).  I applied @valentynberehovyi's changes from that PR to the latest code.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by Arjan-Zuidema** [comment]
Hi @jp-23 Thanks for this PR! Are you done, so I can start testing 🙂

**Comment by jp-23** [comment]
> Hi @jp-23 Thanks for this PR! Are you done, so I can start testing 🙂

Yeah sorry I submitted the PR a tad early, but I am done - you can start testing.

**Comment by jp-23** [comment]
@Arjan-Zuidema I merged in the latest.  It's ready to go.

**Pull request merged**
