### PR TITLE
Adding mavenCentral() as jcenter() is shutting

### PR DESCRIPTION
**Pull request by maheshwarimrinal**
Adding mavenCentral() as jcenter() is shutting down

### CODE REVIEW

**Comment by maheshwarimrinal** [comment]
#340

**Review by HaswinVidanage — APPROVED** [review]

**Comment by HaswinVidanage** [comment]
Can we merge this PR ? 
jcenter is down

**Review by linhqng — APPROVED** [review]
LGTM

**Comment by maheshwarimrinal** [comment]
Any update on this one?

**Comment by vladimirevstratov** [comment]
You can use patch package to fix this issue on post install

**Comment by maheshwarimrinal** [comment]
@tailt94 can we merge this?

**Comment by tailt94** [comment]
@maheshwarimrinal sorry but i'm not maintainer of this library

**Comment by maheshwarimrinal** [comment]
sorry, if you know the maintainer can you tag them would be a great help

**Comment by idrissakhi** [comment]
Resolved in v5.0.0

**Pull request closed without merging**
