### PR TITLE
chore: prepare library for 0.74

### PR DESCRIPTION
**Pull request by WoLewicki**
# Summary

PR bumping the FabricExample to newest RN version and aligning codegen spec so it works correctly there.

## Test Plan

See that the app is building and working correctly.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by Arjan-Zuidema** [comment]
@WoLewicki Thanks for this amazing pull request. Just one quick question; should we wait for the final release of 0.74?

**Comment by WoLewicki** [comment]
Yeah, I think it is reasonable to wait, I don't think there will be any changes affecting the library though 🤞

**Comment by Arjan-Zuidema** [comment]
@WoLewicki 0.74 is out, can you update the PR so we can merge this? 🥳

**Comment by WoLewicki** [comment]
@Arjan-Zuidema done

**Pull request merged**
