### PR TITLE
fix issues and update library

### PR DESCRIPTION
**Pull request by idrissakhi**
# Summary

This library is not maintained since last year. This PR will update and resolve a lot of opened issues, and it will help us all to continue on maintaining this Library.

I need some volunteers to test this branch on real devices, so we can merge it.

This PR will solve the following issues:

#393 #397 #322 #244 #276 #400 #403 #135 

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by thanggggg1** [comment]
image

**Comment by bartolkaruza** [comment]
there is some issue in the ci build step, would be good to resolve that to let the other build steps proceed

**Comment by bartolkaruza** [comment]
also thanks for this effort! This is much needed!

**Comment by bartolkaruza** [comment]
@doranteseduardo @lukebrandonfarrell @MarcoScabbiolo @mikbry @Naturalclar

**Comment by thanggggg1** [comment]
> also thanks for this effort! This is much needed!


> @doranteseduardo @lukebrandonfarrell @MarcoScabbiolo @mikbry @Naturalclar



> also thanks for this effort! This is much needed!

Yes, i hope this version can listen to library changes.i'm having a problem where the CameraRoll doesn't update when i select "selected limited photos" on ios 14

**Comment by thanggggg1** [comment]
Do you have solution for this
image

**Comment by idrissakhi** [comment]
@thanggggg1 can you test again please pushed a new code 😉🙂

**Comment by thanggggg1** [comment]
Yeahh i can yarn it, but found this error when run on xcode. (RNCCameraRollManager.m)
image


> @thanggggg1 can you test again please pushed a new code 😉🙂

**Comment by thanggggg1** [comment]
I try to delete ",false" but cannot get Photos 
image

**Comment by thanggggg1** [comment]
> I try to delete ",false" but cannot get Photos image

Yeah i fix it by change "Import CameraRoll -> Import {CameraRoll}", but it not auto update when i choose images from "Limited Photos" on IOS 14

**Comment by thanggggg1** [comment]
@idrissakhi In IOS 14 I select "Allow access just to the selected pictures" from Setting Apps.
I use openlimitedphotoLibraryPicker from "react-native-permission" to "Add more photos" and after add done the CameraRoll need reload to update

**Comment by idrissakhi** [comment]
@thanggggg1 you don't need to use react-native-permission anymore i already added the CameraRollIOSPermissionModule that allow you to listen and open selection on ios 14

to listen to changes, you need to call the refetch you made.
`
  useEffect(() => {
    let subscription: EmitterSubscription;
    if (isAboveIOS14) {
      subscription = cameraRollEventEmitter.addListener('onLibrarySelectionChange', (_event) => {
        getUnloadedPictures();
      });
    }

    return () => {
      if (isAboveIOS14 && subscription) {
        subscription.remove();
      }
    };
  }, [getUnloadedPictures]);
`

to open selection => 
`
import { iosRefreshGallerySelection } from 'react-native-cameraRoll'
iosRefreshGallerySelection()
`

i will update readMe to include new features later. i am little bit underwater

**Comment by idrissakhi** [comment]
@thanggggg1  you need to listen to event and reload manually your images

`
  useEffect(() => {
    let subscription: EmitterSubscription;
    if (isAboveIOS14) {
      subscription = cameraRollEventEmitter.addListener('onLibrarySelectionChange', (_event) => {
        getUnloadedPictures(); // your method to relaod all images.
      });
    }

    return () => {
      if (isAboveIOS14 && subscription) {
        subscription.remove();
      }
    };
  }, [getUnloadedPictures]);
`

also you don't need extra lib anymore to open native refresh selection modal, i added a method allowing you to open it => 

`iosRefreshGallerySelection`

you can check CameraRollIOSPermission module for all the available methods 🙂😉

**Comment by thanggggg1** [comment]
Thank you very much, finally i done it. I research it for a month and i knew that many people are struggle with this problem. You should public this feature soon.
Very appreciate!!! 👏👏👏👏

image

image

**Comment by idrissakhi** [comment]
@bartolkaruza i can't publish to NPM, would you give me access please

**Pull request merged**
