### PR TITLE
Issue 423: Fix save video on Android

### PR DESCRIPTION
**Pull request by hwth**
# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [x] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Review by idrissakhi — APPROVED** [review]
well done ☑️ ✅

**Comment by Saqib-Rehman-GitH** [comment]
How can i use this in the project. Please guide.

**Comment by ishubhamx** [comment]
can someone merge this

**Comment by hwth** [comment]
> How can i use this in the project. Please guide.

@Saqib-Rehman-GitH you can try my fork for now:
`yarn add git+https://github.com/hwth/react-native-cameraroll.git`

**Comment by idrissakhi** [comment]
Merged ...... 🥳

**Pull request merged**
