### PR TITLE
fix: Remove fbjs in favor of `invariant` lib

### PR DESCRIPTION
**Pull request by mrousavy**
# Summary

Build in my app fails because `fbjs` require cannot be resolved. Instead, it should be added to this pacakge's dependencies. But since we only use invariant, I added invariant instead of fbjs.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by nvojnovic** [comment]
Please merge this.

**Comment by zuhair-naqvi** [comment]
Please merge this.

**Comment by alois-beto** [comment]
any news on when this PR will be merge ?

**Comment by idrisssakhi** [comment]
I re-write the lib to propose new features and resolve most important opened issues → https://www.npmjs.com/package/react-native-photo-gallery-api

**Pull request merged**
